### ISSUE TITLE
🚀 Feature: Allow specifying multiple TS versions (node_modules/typescript paths)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/eslint-plugin-expect-type#107]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Porting over from https://github.com/microsoft/DefinitelyTyped-tools/issues/858: `@definitelytyped/expect` has the ability to receive a `versionsToTest` option. That option contains an array of TS versions with paths to the `node_modules`. The plugin then runs roughly:

```ts
for (const version of versionsToTest) {
  const ts = require(version.path) as TSModule;
  const program = getProgram(tsconfigPath, ts, version.versionName, parserServices.program);
```

Let's port that feature over to `eslint-plugin-expect-type`. I think it can exist roughly as-is. Maybe some bikeshedding on the option name?

### Additional Info

Edit: This would support https://github.com/react-native-community/discussions-and-proposals/issues/719#issuecomment-1769855005 too.

Edit: ...and https://github.com/microsoft/DefinitelyTyped-tools/issues/440

**Comment by jakebailey** [comment]
Related: https://github.com/microsoft/DefinitelyTyped-tools/pull/848

I'm not sure how much I like to have an API that accepts a path to `require`, however, doing this opens the door to us moving the copies somewhere else which is pretty helpful.

**Comment by JoshuaKGoldberg** [comment]
@nateshmbhat no, if there's an update you'll see it in this issue. I haven't had time to work on #123 this year yet. Since you're interested, feel free to send your own PR that builds on #123 to resolve the issue. 🙂
