### ISSUE TITLE
Running eslint without --fix still updates snapshots

### ISSUE THREAD

**Issue by BatuhanW** [JoshuaKGoldberg/eslint-plugin-expect-type#14]
Thanks for the great library!

The issue is, I'm changing one of the test types expecting them to throw an error. Then running eslint without `--fix` option. It still updates snapshots.

Edit: I found out that explicitly setting `"expect-type/expect": ["error", { "disableExpectTypeSnapshotFix": false }]` fixes the issue. It only generates snapshots with --fix.

Having no rule at all doesn't prevent snapshots to be generated.

**Comment by JoshuaKGoldberg** [comment]
I suspect this is the triggering code:

```
// Trick: Function `fix` is ALWAYS run, and result is collected. However RuleFix objects are only read if `--fix` is passed
          get text() {
            if (!applied) {
              // Make sure we update snapshot only on first read of this object
              applied = true;
              if (!options.disableExpectTypeSnapshotFix) {
                updateTypeSnapshot(fileName, snapshotName, actual);
              }
            }
            return '';
          },
```

Since then (2 years ago) ESLint has probably added some call to `.text`.

**Comment by JoshuaKGoldberg** [comment]
Adding the `hacktoberfest` label to this. I don't think it's a particularly easy issue (not `good first issue`), but we'll see. 😄

**Comment by JoshuaKGoldberg** [comment]
I'd asked about this in the ESLint Discord: https://discord.com/channels/688543509199716507/711686958635548723/1107343559981551788. Nothing we can use here was mentioned. Ah well.
