### ISSUE TITLE
🚀 Feature: Twoslash type checks have inconsistent type alias name substitutions behavior across project references

### ISSUE THREAD

**Issue by swachter** [JoshuaKGoldberg/eslint-plugin-expect-type#155]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I have a `Customization<From, To>` type that calculates what can/must be provided in order to transform a value of type `From` into a value of type `To`. This type can conveniently be checked by twoslash checks, e.g.:
```
const x1: Customization<{}, { x: number }> = {} as any;
//    ^? const x1: {
//           x: number;
//       }
const x2: Customization<{}, { x?: number }> = {} as any;
//    ^? const x2: {
//           x?: number | undefined;
//       }
```
Unfortunately, when the `Customization` type is imported from an external dependency then the twoslash checks fail. The type returned in the quick info stays unchanged:
```
const x1: Customization<{}, { x: number }> = {} as any;
//    ^? const x1: Customization<{}, {
//           x: number;
//       }>
const x2: Customization<{}, { x?: number }> = {} as any;
//    ^? const x2: Customization<{}, {
//           x?: number | undefined;
//       }>
```
However, when hovering over `x1` and `x2` in VSCode or IntelliJ, the reduced representation is still shown.
It would be great, if the language service that is used by twoslash checks would be configured in such a way that it returns the same quick info that IDEs show.

### Additional Info

Attached you find a GIF that show how the quick info shown by IntelliJ differs from the quick info used by the twoslash check.
![Screencast from 23 02 2024 19 15 19](https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type/assets/540079/8c8da5f5-0656-48d6-98e1-7fe179bb7ef7)

**Comment by JoshuaKGoldberg** [comment]
It's hard to evaluate this without a reproduction. I appreciate the snippets & gif but really need to see source code with `Customization`'s implementation and with it imported from another place.

https://antfu.me/posts/why-reproductions-are-required

Could you post that please?

**Comment by StefanWachter1507** [comment]
Hi @JoshuaKGoldberg , thanks for looking into this! I prepared a small [repo](https://github.com/swachter/customization) that shows the situation.

**Comment by JoshuaKGoldberg** [comment]
Fascinating, thanks for that! Simplifying and summarizing the reproduction a bit:

```js
import { Customization } from "@monorepo/utils/customization";

declare const x1: Customization<{}, { x: number }>;
//            ^? const x1: {
//                   x: number;
//               }
```

So the two cases are:
* ✅ The source file file is inside `package/utils`, importing `Customization` from `customization.mjs`
* ❌ The source file in a separate project, importing `Customization` from a project reference `customization.d.mts`

The issue also does not reproduce if we make a new `packages/utils/test-d/example.d.ts` next to `packages/utils/test-d/customization.test-d.mts` containing the `Customization` type, and switch the import to `import type { Customization } from "./example.d.ts"`.

I think the conclusion is that this is just _the_ behavior for TypeScript project references. `eslint-plugin-expect-type`'s `expect` rule directly calls to TypeScript's APIs:

https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type/blob/740cd7814cd06a9924df4e0087cf0c79fb3cb27b/src/failures/getExpectTypeFailures.ts#L40-L46

...so there's nothing we can do here to "fix" this 😞.

My advice would be that if you truly think this is a bug in TypeScript, try filing an issue on them. I haven't personally verified that this isn't something that was discussed previously, though - you'll want to check on the TypeScript issue tracker for past discussions. Maybe there's a good reason for this?

Thanks for using the lint rule & filing this issue, at least. It was a fun investigation! 🙌

**Comment by StefanWachter1507** [comment]
Thanks for looking into the issue. The only thing I wonder about is, why do IDEs behave differently? I would suspect, that they also just rely on `tsc` and do not apply additional logic.

**Comment by JoshuaKGoldberg** [comment]
Yeah, I think that's exactly it. Their language service treat types across project references differently from how the CLI would.
