### ISSUE TITLE
Support twoslash syntax (`^?`)

### ISSUE THREAD

**Issue by danvk** [JoshuaKGoldberg/eslint-plugin-expect-type#43]
### 🚀 Feature Request

This plugin uses dtslint-style syntax for type assertions (`$ExpectError`). But twoslash syntax (`^?`) seems to be getting lots of adoption lately (including on the TypeScript playground) and it could also be a good fit here. It neatly dodges the question of "what exactly am I asserting the type of?" by making it incredibly explicit.

#### Existing Behavior

```ts
const square = (x: number) => x * x;
const four = square(2);  // $ExpectType number
```

#### Change Proposal

```ts
const square = (x: number) => x * x;
const four = square(2);
//    ^? const four: number
```

A fix mode to automatically fill these types in (ala the TS playground) would also be rad, but that's for a different feature request.

**Comment by JoshuaKGoldberg** [comment]
I like this a lot. It does make a lot of sense. Let's let it sit for a bit to see if anybody has more thoughts?

**Comment by orta** [comment]
( Some implementation details, this is where we [pick up the hint](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground/src/twoslashInlays.ts#L18-L22) and [here is where we make queries](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/ts-twoslasher/src/index.ts#L522-L553) )

**Comment by JoshuaKGoldberg** [comment]
Heck, let's do it 🔥
