### ISSUE TITLE
TypeScript 4.8 compatibility

### ISSUE THREAD

**Issue by cexbrayat** [JoshuaKGoldberg/eslint-plugin-expect-type#60]
### 🐛 Bug Report

- `eslint-plugin-expect-type` version: 0.2.0
- ESLint version: 8.23.0
- Node version: 16.17.0

#### Actual Behavior

Bumping projects to TS v4.8 makes the plugin error

```
/Users/cedric/Code/ninjasquad/examples/node_modules/typescript/lib/typescript.js:167586
                fileExists: function (fileName) { return host.fileExists(fileName); },
                                                              ^

TypeError: Error while loading rule 'expect-type/expect': host.fileExists is not a function
```

#### Expected Behavior

It would be awesome to support the latest TS version.

#### Reproduction

It looks like bumping TS in the package.json of the plugin repo, and running `npm test` reproduces the issue:

```
 FAIL  tests/rules/twoslash.test.ts
  ● Test suite failed to run

    src/rules/expect.ts:507:3 - error TS2739: Type '{ getCompilationSettings: () => CompilerOptions; getCurrentDirectory: () => string; getDefaultLibFileName: () => string; getScriptFileNames: () => string[]; getScriptSnapshot: (name: string) => IScriptSnapshot; getScriptVersion: () => string; }' is missing the following properties from type 'LanguageServiceHost': readFile, fileExists

    507   return {
          ~~~~~~~~
    508     getCompilationSettings: () => program.getCompilerOptions(),
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...
    513     getScriptVersion: () => '1',
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    514   };
        ~~~~
```

**Comment by danvk** [comment]
The issue is that `readFile` and `fileExiststs` are now required properties on `LanguageServiceHost`. Here's where that change was made in TS, it looks like it has something to do with supporting ESM: https://github.com/microsoft/TypeScript/pull/47495/files#diff-9717eb6d935579eea3b5662088dd258d4e1e17e2a405c3f1fa431e981e01b08fR268
