### ISSUE TITLE
Tabs are not considered whitespace for checking a comment's line index

### ISSUE THREAD

**Issue by colinking** [JoshuaKGoldberg/eslint-plugin-expect-type#64]
### 🐛 Bug Report

- `eslint-plugin-expect-type` version: 0.2.1
- ESLint version: 8.27.0
- Node version: 18

#### Actual Behavior

If code is indented with tabs, this plugin produces "Can not match a node to this assertion" errors.

I've also seen issues with `--fix` where lines in tab-indented code get duplicated. That appears related, but I don't have a reliable reproduction.

#### Expected Behavior

Code indented with tabs should work the same as that indented with spaces.

#### Reproduction

https://github.com/colinking/repros-eslint-plugin-expect-type/tree/main/tabs

Run `npm run lint -- --fix` to run `eslint`. Notice the lines that are indented with spaces are validated correctly, but the lines indented with tabs produce the errors.

**Comment by JoshuaKGoldberg** [comment]
Sorry for the delay here @colinking - I'd neglected to watch this repository 😓. Thanks for posting the bug! Accepting PRs to fix this case. I've slowly started moving my repos to tabs and would very much appreciate this plugin working for them. 😄

**Comment by JoshuaKGoldberg** [comment]
Sorry for the delay here @colinking - I'd neglected to watch this repository 😓. Thanks for posting the bug! Accepting PRs to fix this case. I've slowly started moving my repos to tabs and would very much appreciate this plugin working for them. 😄

**Comment by JoshuaKGoldberg** [comment]
Sorry for the delay here @colinking - I'd neglected to watch this repository 😓. Thanks for posting the bug! Accepting PRs to fix this case. I've slowly started moving my repos to tabs and would very much appreciate this plugin working for them. 😄

**Comment by JoshuaKGoldberg** [comment]
FYI @colinking, this should be fixed in `@eslint-plugin-expect-type@0.2.3`. Please let me know if that's not the case!
